[package]
name = "stembed-cli"
version = "0.1.0"
edition = "2021"
authors = ["Til Blechschmidt <til@blechschmidt.dev>"]

[dependencies]
stembed = { path = "../stembed", features = ["compile", "desktop"] }
clap = { version = "3.0", features = ["derive"] }
