[package]
name = "cofit"
version = "0.1.0"
edition = "2021"

[features]
usb = ["std", "hidapi", "tokio"]
std = []

[dependencies]
hidapi = { version = "1.4.1", optional = true }
tokio = { version = "1.20", features = ["sync"], default-features = false, optional = true }
